### ISSUE TITLE
feat: create signup route

### ISSUE THREAD

**Issue by r3yc0n1c** [r3yc0n1c/flipkart-clone#1]
- Create `server.js` in the root folder 
- Add a signup route using `express` as the backend service

**Comment by AadeshKabra** [comment]
Hi Can I work on this?

**Comment by SINJINI-G** [comment]
Can I add this feature?
I am experienced in node and express.

**Comment by r3yc0n1c** [comment]
Hi guys! can you share your route details here? I'm thinking about some basic params which we can use for login also... suggestions are most welcome

**Comment by SINJINI-G** [comment]
I think name, email and password are the basic parameters that will suffice as of now. Later we can add mobile number and OTP verification.

**Comment by r3yc0n1c** [comment]
GTG! assigning it to you @SINJINI-G All the best!

**Comment by r3yc0n1c** [comment]
closing this issue
