### ISSUE TITLE
update: delete user from mongodb

### ISSUE THREAD

**Issue by r3yc0n1c** [r3yc0n1c/flipkart-clone#17]
Modify the `/delete` route to remove entries from our DB

**Comment by ron-huberfeld** [comment]
Hi @r3yc0n1c, 
Can I have this?

**Comment by r3yc0n1c** [comment]
yeah sure! go ahead

**Comment by ron-huberfeld** [comment]
Hi @r3yc0n1c 
Please review [PR](https://github.com/r3yc0n1c/flipkart-clone/pull/18)

**Comment by ron-huberfeld** [comment]
Hi @r3yc0n1c 
Please review [PR](https://github.com/r3yc0n1c/flipkart-clone/pull/19)

**Comment by ron-huberfeld** [comment]
Thanks @r3yc0n1c 
I believe you can close this issue

**Comment by r3yc0n1c** [comment]
sure!
