### ISSUE TITLE
feat: Create Login route

### ISSUE THREAD

**Issue by SINJINI-G** [r3yc0n1c/flipkart-clone#2]
Add Login route with parameters depending on signup feature followed by email and password verification.

**Comment by SINJINI-G** [comment]
Can I work on this issue?

**Comment by r3yc0n1c** [comment]
sure but complete the signup feat 1st!

**Comment by SINJINI-G** [comment]
Issue #1 has been resolved. Will you please assign this issue to me?

**Comment by r3yc0n1c** [comment]
sure! go ahead!
